### ISSUE TITLE
How do I update to 1.16

### ISSUE THREAD

**Issue by Xertxert** [zxl777/V86-and-MineServer#2]
How do I update my server

**Comment by glebia** [comment]
wait while hosting updates vanilla version

**Comment by Xertxert** [comment]
What do you mean

**Comment by Xertxert** [comment]
Again I’m sorry if you didn’t catch my last message but do you mean the people that on the app is going to update the server

**Comment by Xertxert** [comment]
Replace on with owner

**Comment by glebia** [comment]
Yes owner need to update server to 1.16

**Comment by Xertxert** [comment]
Ok thank you for being helpful if you say to close it than I will

**Comment by zxl777** [comment]
We are waiting for server core update.
V86 server core update news following this URL https://github.com/Element-0/ElementZero/releases
MineServer server core update news following this URL https://github.com/pmmp/PocketMine-MP/releases

**Comment by oma945** [comment]
I have the same question too, when do you think the update will be available because I cannot use my server Until it is updated.

**Comment by oma945** [comment]
Also, the command function on the V86 app doesn’t seem to be working.... its not giving me any indication of anything happening once I send a command out

**Comment by zxl777** [comment]
We can only wait patiently for the server core to be updated now. According to previous experience, it can be updated within 7 days.

@oma945 ,What's you server port?

**Comment by oma945** [comment]
@zxl777  is there a way I can send it to you privately? I don’t want any unwelcome guests on my server if possible.

**Comment by zxl777** [comment]
> @zxl777 is there a way I can send it to you privately? I don’t want any unwelcome guests on my server if possible.

No privately message here.
We have plans to develop whitelist and blacklist functions, such functions can meet your needs.

**Comment by oma945** [comment]
Ok @zxl777 my port is 5136

**Comment by zxl777** [comment]
V86 and MineServer core updated. Now 1.60 worked.

Due to the update of MineServer ( pmmp core ) some of your server plugins may not work for you. 
So if your Server isn't working because of a broken plugin, try going into console and seeing what plugin is causing it to happen.

**Comment by oma945** [comment]
Thank you!
