### ISSUE TITLE
Usually it takes about 10 try’s before it connects to the server and sometimes requires a restart

### ISSUE THREAD

**Issue by oma945** [zxl777/V86-and-MineServer#4]

**Comment by oma945** [comment]
Is there a way I could make it easier to get on?

**Comment by zxl777** [comment]
60% is a Minecraft problem, 10% is a Wi-Fi problem, and 30% is a server problem.
Generally, you can switch the Minecraft menu first, or switch Wi-Fi and try again.
We will continue to optimize the server to reduce the possibility of this 30%.

**Comment by zxl777** [comment]
Open V86 App - Command - Help - Send
If showed  "Showing help page 1 of 3" ,Then the server is online.
You just need to try your Minecraft side.

**Comment by oma945** [comment]
Ok, thank you
